config/routes.rb
Rails.application.routes.draw do
  root :to => 'beers#index'

  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :destroys
  resources :users
	resources :beers
	resources :breweries
	resources :ratings

  resource :session, only: [:new, :create, :destroy]
  get 'places', to: 'places#index'
  post 'places', to:'places#search'
  resources :places, only:[:index, :show]
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  # Togglet
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :users do
    post 'froze_and_activate', on: :member
  end
  resources :beer_clubs do
    post 'toggle_confirmed', on: :member
  end

  # JS Toiminnallisuus
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#nglist'
  get 'ngbeerlist', to:'beers#nglist'
end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
  has_many :memberships, dependent: :destroy
  has_many :members, -> { distinct }, through: :memberships, source: :user
  validates :name, presence: true
  validates :city, presence: true
  validates :founded, numericality: { greater_than_or_equal_to: 1600, only_integer: true}
  validate :founded_in_future

  def founded_in_future
    if founded > Time.now.year
      errors.add(:founded, "can't be in the future")
    end
  end

  def to_s
    "#{name} #{city}"
  end

  def isMember(user)
    membership = self.memberships.find_by(user_id: user.id, beer_club_id: self.id)

    if membership.nil?
      return false
    end

    return membership.confirmed
  end

  def isApplied(user)
    membership = self.memberships.find_by(user_id: user.id, beer_club_id: self.id)

    if membership.nil?
      return false
    end

    return !membership.confirmed
  end
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]
  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    if current_user && @beer_club.members.exclude?(current_user)
      @membership = Membership.new
      @membership.user = current_user
      @membership.beer_club = @beer_club
    end

    if current_user && @beer_club.members.include?(current_user)
      @membership = Membership.find_by(user_id: current_user.id, beer_club_id:@beer_club.id)
    end
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render :show, status: :created, location: @beer_club }
        membership = Membership.new(user_id: current_user.id, beer_club_id: @beer_club.id, confirmed: true)
        membership.save
      else
        format.html { render :new }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    if is_admin
      @beer_club.destroy
      respond_to do |format|
        format.html { redirect_to beer_clubs_url, notice: 'Beer club was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to beer_clubs_url, notice: 'Only admins can do that!' }
        format.json { head :no_content }
      end
    end
  end

  def toggle_confirmed
    membership = Membership.find_by(user_id: params[:user_id], beer_club_id: params[:beer_club_id])
    membership.update_attribute :confirmed, true
    redirect_to :back, notice: 'Membership accepted!'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer_club
      @beer_club = BeerClub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_club_params
      params.require(:beer_club).permit(:name, :founded, :city, :id)
    end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_for(@beer_club) do |f| %>
  <% if @beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% @beer_club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :founded %><br>
    <%= f.number_field :founded, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city, class:'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing beer_club</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer_club, class:'btn btn-default btn-xs' %> |
<%= link_to 'Back', beer_clubs_path, class:'btn btn-default btn-xs' %>

app/views/beer_clubs/index.html.erb
<h1>Listing beer_clubs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Founded</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= beer_club.name %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
        <td><%= link_to 'Show', beer_club %></td>
        <td><%= link_to 'Edit', edit_beer_club_path(beer_club) %></td>
        <td><%= link_to 'Destroy', beer_club, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer club', new_beer_club_path, class:'btn btn-default btn-xs' %>

app/views/beer_clubs/new.html.erb
<h1>New club</h1>

<%= render 'form' %>

<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @beer_club.name %></h1>

<p>
  <strong>Founded:</strong>
  <%= @beer_club.founded %>
</p>

<p>
  <strong>City:</strong>
  <%= @beer_club.city %>
</p>

<% if @beer_club.members %>
    <h3>Members</h3>

    <ul>
      <% @beer_club.members.each do |member| %>
          <li> <%= link_to member.username, user_path(member) %> </li>
      <% end %>
    </ul>
<% end %>

<% if current_user %>
  <% if @beer_club.isMember(current_user) %>
      <h3>Outstanding applications</h3>
          <ul>
            <% @beer_club.memberships.each do |membership|  %>
                <% usr = @beer_club.members.find_by id: membership.user_id %>
                <%if !@beer_club.isMember(usr) %>
                      <li>
                        <%= usr.username %>
                        <%= link_to 'Confirm' , toggle_confirmed_beer_club_path(:user_id => membership.user_id,:beer_club_id => membership.beer_club_id), method: :post, class:'btn btn-success btn-xs' %>
                      </li>
                <% end %>
            <% end %>
          </ul>
  <% end %>
<% end %>

<p>
  <% if current_user && @beer_club.members.exclude?(current_user) %>
      <%= form_for(@membership) do |f| %>
          <%= f.hidden_field :beer_club_id %>
          <%= f.submit value: 'join the club' %>
      <% end %>
  <% end %>

  <% if current_user && @beer_club.members.include?(current_user) %>
    <%= form_for(@membership, method: "delete") do |f| %>
       <%= f.hidden_field :beer_club_id %>
       <%= f.submit value: 'end the membership', class:'btn btn-danger btn-xs'  %>
    <% end %>
  <% end %>
</p>

<%= link_to 'Edit', edit_beer_club_path(@beer_club), class:'btn btn-default btn-xs' %>
<%= link_to 'Destroy', @beer_club, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-default btn-xs' %>