config/routes.rb
Rails.application.routes.draw do
  root :to => 'beers#index'

  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :destroys
  resources :users
	resources :beers
	resources :breweries
	resources :ratings

  resource :session, only: [:new, :create, :destroy]
  get 'places', to: 'places#index'
  post 'places', to:'places#search'
  resources :places, only:[:index, :show]
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  # Togglet
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :users do
    post 'froze_and_activate', on: :member
  end
  resources :beer_clubs do
    post 'toggle_confirmed', on: :member
  end

  # JS Toiminnallisuus
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#nglist'
  get 'ngbeerlist', to:'beers#nglist'
end

app/models/user.rb
class User < ActiveRecord::Base
  include RatingAverage

  validates :username, uniqueness: true,
                       length: { minimum: 3, maximum: 15 }

  validates :password, length: { minimum: 4 },
                       format: {
                          with: /\d.*[A-Z]|[A-Z].*\d/,
                          message: "has to contain one number and one upper case letter"
                       }

  has_many :ratings, dependent: :destroy
  has_many :beers, through: :ratings
  has_many :memberships
  has_many :beer_clubs, through: :memberships

  has_secure_password

  def favorite_beer
    return nil if ratings.empty?
    ratings.order(score: :desc).limit(1).first.beer
  end

  def favorite_style
    favorite :style
  end

  def favorite(category)
    return nil if ratings.empty?
    rated = ratings.map{ |r| r.beer.send(category) }.uniq
    rated.sort_by { |item| -rating_of(category, item) }.first
  end

  def rating_of(category, item)
    ratings_of = ratings.select{ |r| r.beer.send(category)==item }
    ratings_of.map(&:score).inject(&:+) / ratings_of.count.to_f
  end

  def favorite_brewery
    return nil if ratings.empty?
    h = Brewery.joins(:ratings, :beers).select("breweries.name, ratings.score").group("breweries.name").average(:score)
    Brewery.find_by(name: h.key(h.values.max))
  end

  def most_active_users(n)
    h = User.joins(:ratings).select("users.username, rating.user_id").group(:username).count(:user_id).sort_by {|k,v| v}.reverse[0..n]
    hash = {}
      h.each do |key, value|
        u = User.find_by(:username => key)
        hash[u] = value
      end
    hash
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:beers, :ratings).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? and current_user == @user and @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if current_user == @user
      @user.destroy
      session[:user_id] = nil
    end
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def froze_and_activate
    if current_user.admin
      user = User.find(params[:id])
      user.update_attribute :froze, (not user.froze)
      new_status = user.froze? ? "frozen" : "activated"

      redirect_to :back, notice:"Users account has been #{new_status}"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :admin, :froze)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div class="field">
      <%= f.label :username %><br />
      <%= f.text_field :username, class:'form-control' %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, class:'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password of <%= @user.username %> </h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
      <th><!-- Frozen? --></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td> <% if user.froze %><span class="label label-info">account frozen</span><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class:'btn btn-default btn-xs' %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.username %>
  <% if @user.froze %>
    <span class="label label-info">account frozen</span>
  <% end %>
  <% if @user.admin %>
    <span class="label label-danger">admin</span>
  <% end %>
</h1>

<p>has made <%= pluralize(@user.ratings.count, 'rating') %> ratings</p>

<% if @user.favorite_brewery %>
    <p>Favorite brewery: <%= link_to @user.favorite_brewery.name, brewery_path(@user.favorite_brewery) %></p>
<% end %>

<% if @user.favorite_style %>
<p>Favorite style: <%= link_to @user.favorite_style, style_path(@user.favorite_style) %></p>
<% end %>

<% if @user.beer_clubs %>
    <h3>Member of</h3>
    <ul>
      <% @user.beer_clubs.each do |beer_club| %>
          <li> <%= link_to beer_club.name, beer_club_path(beer_club)%> </li>
      <% end %>
    </ul>
    <h3>applied membership of</h3>
    <ul>
      <% @user.beer_clubs.each do |club| %>
          <%if club.isApplied(@user) %>
            <li><%= link_to club.name, beer_club_path(club) %></li>
          <% end %>
      <% end %>
    </ul>
<% end %>

<% if @user.ratings %>
<h3>Ratings</h3>
<ul>
  <% @user.ratings.each do |rating| %>
    <li> <%= rating %>
      <% if @user == current_user %>
        <%= link_to 'delete', rating, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-default btn-xs' %></li>
      <% end %>
  <% end %>
</ul>
<% end %>
<br />
<%= link_to "change account status", froze_and_activate_user_path(@user.id), method: :post, class: "btn btn-danger btn-xs" if current_user && current_user.admin %>
<% if @user == current_user %>
  <%= link_to 'Edit', edit_user_path(@user), class:'btn btn-default btn-xs' %>
<% end %>