config/routes.rb
Rails.application.routes.draw do
  root :to => 'beers#index'

  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :destroys
  resources :users
	resources :beers
	resources :breweries
	resources :ratings

  resource :session, only: [:new, :create, :destroy]
  get 'places', to: 'places#index'
  post 'places', to:'places#search'
  resources :places, only:[:index, :show]
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  # Togglet
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :users do
    post 'froze_and_activate', on: :member
  end
  resources :beer_clubs do
    post 'toggle_confirmed', on: :member
  end

  # JS Toiminnallisuus
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#nglist'
  get 'ngbeerlist', to:'beers#nglist'
end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  include RatingAverage

  validates :name, presence: true
  validates :year, numericality: { less_than_or_equal_to: ->(_) { Time.now.year} }

  scope :active, -> { where active:true }
  scope :retired, -> { where active:[nil,false] }

  has_many :beers, :dependent => :destroy
  has_many :ratings, :through => :beers
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :list]
  before_action :skip_if_cached, only: [:index]

  # GET /breweries
  # GET /breweries.json
  def index
    @breweries = Brewery.all
    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired


    order = params[:order] || 'name'

    if order == 'name'
      @active_breweries = @active_breweries.sort_by{ |b| b.name }
      @retired_breweries = @retired_breweries.sort_by{ |b| b.name }
    elsif order == 'year'
      if session[:list_ord]
        @active_breweries = @active_breweries.sort_by{ |b| b.year }.reverse
        @retired_breweries = @retired_breweries.sort_by{ |b| b.year }.reverse
        session[:list_ord] = false
      else
        @active_breweries = @active_breweries.sort_by{ |b| b.year }
        @retired_breweries = @retired_breweries.sort_by{ |b| b.year }
        session[:list_ord] = true
      end
    end
  end

  def list
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    expire_frags
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    expire_frags
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    expire_frags
    if is_admin
      @brewery.destroy
      respond_to do |format|
        format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to beer_clubs_url, notice: 'Only admins can do that!' }
        format.json { head :no_content }
      end
    end
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, (not brewery.active)

    new_status = brewery.active? ? "active" : "retired"

    redirect_to :back, notice:"brewery activity status changed to #{new_status}"
  end

  def skip_if_cached
    @order = params[:order] || 'name'
    return render :index if fragment_exist?( "brewerylist-#{@order}"  )
  end

  private

    def expire_frags
      ["brewerylist-name", "breweylist-year"].each{ |f| expire_fragment(f) }
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :year, :active)
    end

    def authenticate
      admin_accounts = { "admin" => "secret", "pekka" => "beer", "arto" => "foobar", "matti" => "ittam"}
      authenticate_or_request_with_http_basic do |username, password|
        admin_accounts.has_key?(username) and admin_accounts[username] = password
      end
    end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/breweries/_list.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th><%= link_to 'Name', breweries_path(order:"name") %></th>
    <th><%= link_to 'Year', breweries_path(order:"year") %></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
        <td><%= link_to 'Edit', edit_brewery_path(brewery) %></td>
        <td><%= link_to 'Destroy', brewery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/breweries/edit.html.erb
<h1>Editing brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery, class:'btn btn-default btn-xs' %>
<%= link_to 'Back', breweries_path, class:'btn btn-default btn-xs' %>

app/views/breweries/index.html.erb
<h1>Listing breweries</h1>

<h2>Active</h2>

<p> Number of active breweries: <%= @active_breweries.count %> </p>

<%= render 'list', breweries: @active_breweries %>

<h2>Retired</h2>

<p> Number of retired breweries: <%= @retired_breweries.count %> </p>

<%= render 'list', breweries: @retired_breweries %>

<br>

<%= link_to 'New Brewery', new_brewery_path, class:'btn btn-default btn-xs' %>
<%= link_to 'List of Beers', beers_path, class:'btn btn-default btn-xs' %>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path, class:'btn btn-default btn-xs' %>

app/views/breweries/nglist.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular.min.js"></script>
<script>
  var myApp = angular.module('myApp', []);

  myApp.controller("BreweriesController", function ($scope, $http) {
    $http.get('breweries.json').success( function(data, status, headers, config) {
      $scope.breweries = data;
    });

    $scope.order = 'name';

    $scope.sort_by = function (order){
      $scope.order = order;
      console.log(order);
    }

    $scope.searchText = '';
  });
</script>

<h2>Breweries</h2>

<div ng-app="myApp" ng-controller="BreweriesController">

  search:  <input ng-model="searchText">

  <table class="table table-hover">
    <thead>
    <th> <a ng-click="sort_by('name')">Name</a> </th>
    <th> <a ng-click="sort_by('year')">Year</a> </th>
    </thead>
    <tr ng-repeat="brewery in breweries| orderBy:order | filter:searchText">
      <td>{{brewery.name}}</td>
      <td>{{brewery.year}}</td>
    </tr>
  </table>

</div>

app/views/breweries/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @brewery.name %>
  <% if not @brewery.active  %>
      <span class="label label-info">retired</span>
  <% end %>
</h2>

<p><i>Established in <%= @brewery.year %></i></p>

<p>Number of beers <%= @brewery.beers.count %></p>

<p>
 <% @brewery.beers.each do |beer| %>
   <%= link_to beer.name, beer %><br />
 <% end %>
</p>

<p>
   <% if @brewery.ratings.empty? %>
    Has not yet been rated!
  <% else %>
    Has <%= pluralize(@brewery.ratings.count, 'rating') %>, average <%= @brewery.average_rating %>
  <% end %>
</p>

<%= link_to "change activity", toggle_activity_brewery_path(@brewery.id), method: :post, class: "btn btn-danger btn-xs" %>
<%= link_to 'Edit', edit_brewery_path(@brewery), class:'btn btn-default btn-xs' %>
<%= link_to 'Back', breweries_path, class:'btn btn-default btn-xs' %>